app:
  cache:
    staleness-days: 20
  downstream:
    bureau-url:
    dedupe-url:
    connect-timeout-ms: 3000
    read-timeout-ms: 15000
  gateway:
    ocp-sub-key:
    auth-client-id:
    auth-client-secret:
    auth-token-url:

logging:
  file:
    name: logs/application.log
  level:
    com.bajaj: INFO
